### ISSUE TITLE
Offline Images

### ISSUE THREAD

**Issue by ahmedbilal-2711** [Mishalzahra28/react-app#1]
Hey,
   You have downloaded images for your project. You can just inspect the image tag from the original website and copy the src of the image. Pasting the same src link in your project (in image tag src). This will make the project lighter in weight. 
![src](https://user-images.githubusercontent.com/81642482/180599953-44fa2a06-5dda-43c5-bb0e-92a9f9155b87.png)
 
Click on the link given as shown in image attached and then copy the src from address bar.
Thank You.

**Comment by Mishalzahra28** [comment]
> Hey, You have downloaded images for your project. You can just inspect the image tag from the original website and copy the src of the image. Pasting the same src link in your project (in image tag src). This will make the project lighter in weight. ![src](https://user-images.githubusercontent.com/81642482/180599953-44fa2a06-5dda-43c5-bb0e-92a9f9155b87.png)
> 
> Click on the link given as shown in image attached and then copy the src from address bar. Thank You.

Ok Ok
